export const products = [
    {
      "id": 1,
      "title": "Color 1",
      "description": "Краска Wallquest, Brownsone MS90100",
      "price": 6000,
      "new": true,
      "avaliable": 10,
      "contracts": true,
      "exclusive": true,
      "sale": 5,
      "rating": 4.9,
      "image": './assets/product_1.jpg'
    }, 
    {
      "id": 2,
      "title": "Color 2",
      "description": "Краска Wallquest, Brownsone MS90101",
      "price": 4000,
      "new": true,
      "avaliable": 7,
      "contracts": true,
      "exclusive": true,
      "sale": 0,
      "rating": 4.3,
      "image": './assets/product_2.jpg'
    }, 
    {
      "id": 3,
      "title": "Color 3",
      "description": "Краска Wallquest, Brownsone MS90102",
      "price": 2200,
      "new": true,
      "avaliable": 25,
      "contracts": true,
      "exclusive": true,
      "sale": 25,
      "rating": 4.1,
      "image": './assets/product_3.jpg'
    }, 
    {
      "id": 4,
      "title": "Color 4",
      "description": "Краска Wallquest, Brownsone MS90103",
      "price": 6400,
      "new": true,
      "avaliable": 0,
      "contracts": true,
      "exclusive": true,
      "sale": 10,
      "rating": 2.9,
      "image": './assets/product_4.jpg'
    }, 
    {
      "id": 5,
      "title": "Color 5",
      "description": "Краска Wallquest, Brownsone MS90104",
      "price": 1050,
      "new": true,
      "avaliable": 0,
      "contracts": true,
      "exclusive": true,
      "sale": 0,
      "rating": 3.5,
      "image": './assets/product_5.jpg'
    }, 
    {
      "id": 6,
      "title": "Color 6",
      "description": "Краска Wallquest, Brownsone MS90105",
      "price": 9400,
      "new": true,
      "avaliable": 1,
      "contracts": true,
      "exclusive": true,
      "sale": 0,
      "rating": 4.4,
      "image": './assets/product_6.jpg'
    }, 
    {
      "id": 7,
      "title": "Color 7",
      "description": "Краска Wallquest, Brownsone MS90106",
      "price": 4500,
      "new": false,
      "avaliable": 43,
      "contracts": true,
      "exclusive": true,
      "sale": 0,
      "rating": 4.5,
      "image": './assets/product_7.jpg'
    }, 
    {
      "id": 8,
      "title": "Color 8",
      "description": "Краска Wallquest, Brownsone MS90107",
      "price": 3400,
      "new": true,
      "avaliable": 91,
      "contracts": false,
      "exclusive": true,
      "sale": 0,
      "rating": 5,
      "image": './assets/product_8.jpg'
    }, 
    {
      "id": 9,
      "title": "Color 9",
      "description": "Краска Wallquest, Brownsone MS90108",
      "price": 2300,
      "new": false,
      "avaliable": 14,
      "contracts": true,
      "exclusive": true,
      "sale": 5,
      "rating": 4.1,
      "image": './assets/product_9.jpg'
    }, 
    {
      "id": 10,
      "title": "Color 10",
      "description": "Краска Wallquest, Brownsone MS90109",
      "price": 6500,
      "new": true,
      "avaliable": 54,
      "contracts": false,
      "exclusive": true,
      "sale": 20,
      "rating": 4.9,
      "image": './assets/product_10.jpg'
    }, 
    {
      "id": 11,
      "title": "Color 11",
      "description": "Краска Wallquest, Brownsone MS90110",
      "price": 7600,
      "new": false,
      "avaliable": 0,
      "contracts": true,
      "exclusive": true,
      "sale": 15,
      "rating": 3.9,
      "image": './assets/product_11.jpg'
    }, 
    {
      "id": 12,
      "title": "Color 12",
      "description": "Краска Wallquest, Brownsone MS90111",
      "price": 3460,
      "new": true,
      "avaliable": 32,
      "contracts": false,
      "exclusive": false,
      "sale": 0,
      "rating": 4,
      "image": './assets/product_12.jpg'
    }, 
    {
      "id": 13,
      "title": "Color 13",
      "description": "Краска Wallquest, Brownsone MS90112",
      "price": 7600,
      "new": false,
      "avaliable": 65,
      "contracts": true,
      "exclusive": true,
      "sale": 15,
      "rating": 4.7,
      "image": './assets/product_13.jpg'
    }, 
    {
      "id": 14,
      "title": "Color 14",
      "description": "Краска Wallquest, Brownsone MS90113",
      "price": 3300,
      "new": true,
      "avaliable": 23,
      "contracts": true,
      "exclusive": true,
      "sale": 0,
      "rating": 4.9,
      "image": './assets/product_14.jpg'
    },
    {
      "id": 15,
      "title": "Color 15",
      "description": "Краска Wallquest, Brownsone MS90114",
      "price": 2500,
      "new": true,
      "avaliable": 6,
      "contracts": false,
      "exclusive": false,
      "sale": 10,
      "rating": 4.2,
      "image": './assets/product_15.jpg'
    }
  ]